### ISSUE TITLE
inference is painfully slow

### ISSUE THREAD

**Issue by bruceunx** [edgenai/llama_cpp-rs#51]
I run the example , the inference is much slower than llama.cpp main example or llama-cpp-python. almost 10 times slower (5s/token),  I cannot get the reason as rust should be faster than the python version?

**Comment by nkoppel** [comment]
Make sure that you are running with `cargo run --release`. I'm not quite sure why, but running in debug mode is much slower than running in release.

**Comment by pedro-devv** [comment]
@nkoppel The `llama.cpp` sub-module gets compiled with a configuration matching Cargo's, so with debug symbols and no optimizations applied, this is the default behavior of [cc](https://crates.io/crates/cc). Because `llama.cpp` is so computationally heavy, the lack of optimizations is much more noticeable compared to some other programs.

**Comment by andychenbruce** [comment]
Can also confirm running with `--release` fixes it. Offloaded an entire 33B model to the GPU with CUBLAS and it was only like 1 token every 5 seconds.

Reran with `cargo run --release` and now it makes about 20 words in under 1 second, around a 100x times increase.

I think in the `README.md` there should be a thing saying to run with `--release`.

At least in my program the bottleneck seems to be on 
```rust
ctx.decode(&mut batch).unwrap();
```
taking up almost all the time when on debug build.

**Comment by pedro-devv** [comment]
I will update the documentation to recommend running with `--release`, meanwhile if there are no further problems beyond that, I will close this issue.
